### PR TITLE
add files that will allow muse-lsl to run on a Mac

### PR DESCRIPTION
**Pull request by amandakeasson**

### CODE REVIEW

**Comment by kylemath** [comment]
once this is merged I can also add my other .py tasks I have made in my fork (spatial cueing, eyes open/closed), and their notebooks

**Comment by kylemath** [comment]
@hubertjb @amandakeasson lets chat about this and make a plan, I want to also push my eeg-notebook changes, which build off of @amandakeasson 's PR here, maybe I'll make a PR to compare?

**Comment by kylemath** [comment]
do I need to do something special to push to this repo and make a new pr @jdpigeon @JohnGriffiths

**Comment by JohnGriffiths** [comment]
@kylemath  I will merge the PR but can't test as I don't have a mac.

**Comment by JohnGriffiths** [comment]
@kylemath I had to resolve a few minor merge conflicts. I don't think it should affect your stuff. Please make a new branch off master with your new stuff and PR and I'll merge that also. Thanks for the contributions!

**Comment by kylemath** [comment]
im still having trouble pushing to this repo, shouldn't I just be able to do it? 
@JohnGriffiths 
getting the following error: 
```remote: Permission to NeuroTechX/eeg-notebooks.git denied to kylemath.
fatal: unable to access 'https://github.com/NeuroTechX/eeg-notebooks.git/': The requested URL returned error: 403```

**Comment by JohnGriffiths** [comment]
No you can't push to repos unless you have write privilages

**Comment by JohnGriffiths** [comment]
The standard process is:

- fork on github
- clone your local fork with the "git@github.com:..." syntax
- create a branch for your new changes
- commit your changes on the new branch 
- push the new branch to you github fork
- submit a pull request using the github gui

**Pull request merged**
